# Generated by Django 3.2.4 on 2021-08-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroApp', '0002_remove_vendor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
