# Generated by Django 3.2.4 on 2021-09-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electroApp', '0004_product_onsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand_imgs/')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatagoryBrands', to='electroApp.category')),
            ],
            options={
                'verbose_name_plural': '3. Brands',
            },
        ),
    ]
