# Generated by Django 3.2.4 on 2021-09-11 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroApp', '0006_auto_20210910_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alter_phone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
