# Generated by Django 3.2.4 on 2021-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroApp', '0010_auto_20210915_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MRP',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
