# Generated by Django 3.2 on 2021-11-21 16:05

import IPL_App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=IPL_App.models.upload_cover_to)),
                ('champ_win', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to=IPL_App.models.upload_profile_to)),
                ('price', models.IntegerField()),
                ('isPlaying', models.BooleanField(default=False)),
                ('description', models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('Allrounder', 'Allrounder')], default='Allrounder', max_length=100)),
                ('team', models.ForeignKey(db_column='team', on_delete=django.db.models.deletion.CASCADE, to='IPL_App.team', to_field='teamName')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
